### ISSUE TITLE
Force Close Application After add or edit strings or xml in resources.arsc

### ISSUE THREAD

**Issue by Programmer6666** [REAndroid/ARSCLib#1]
After the changes in the resources.arsc  file (adding a new string or a new XML)

After compiling the Android application, the application encounters a force close error

 the edited application loses its name and its icon after editing and compiling with the new resources.arsc file.

In the logs section, the error is as follows

 java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: android.content.res.Resources$NotFoundException: String resource ID #0x7f0f001b
  at android.app.ActivityThread.installProvider(ActivityThread.java:5858)

Orginal Apk 

https://dl.dropboxusercontent.com/s/y72kyqk8alakz0u/app-release_original.apk?dl=0

Modified Apk

https://dl.dropboxusercontent.com/s/3fyhod67lgvfv1v/app-release-modified.apk?dl=0

**Comment by REAndroid** [comment]
What is your android version ? Seems like you are using android version <= 7 (API 25).

**Comment by Programmer6666** [comment]
> What is your android version ? Seems like you are using android version <= 7 (API 25).


I tested on Android 7, Android 10 and Android 5.1

**Comment by REAndroid** [comment]
> > > > What is your android version ? Seems like you are using android version <= 7 (API 25).
> > > 
> > > 
> > > I tested on Android 7, Android 10 and Android 5.1
> > 
> > 
> > I tested with android 10, its working. Try with android 8 or 9
> 
> I retested on Android 10, 8 and 9 and the app worked successfully
> 
> But it crashes on Android 7 and Android 11 and 12
> 
> Please tell me the reason for this? And is there a solution?

There is unfinished work on class "SpecBlock", IntegerArray mOfset must be updated after change of entries count.
It will be fixed on next commit

**Comment by Programmer6666** [comment]
> > > > > What is your android version ? Seems like you are using android version <= 7 (API 25).
> > > > 
> > > > 
> > > > I tested on Android 7, Android 10 and Android 5.1
> > > 
> > > 
> > > I tested with android 10, its working. Try with android 8 or 9
> > 
> > 
> > I retested on Android 10, 8 and 9 and the app worked successfully
> > But it crashes on Android 7 and Android 11 and 12
> > Please tell me the reason for this? And is there a solution?
> 
> There is unfinished work on class "SpecBlock", IntegerArray mOfset must be updated after change of entries count. It will be fixed on next commit


Thanks for your attention
i hope this problem will be solved soon

**Comment by REAndroid** [comment]
Fixed on [this commit](https://github.com/REAndroid/ARSCLib/commit/4fe4657f9fd2ec6f3a5fb1ec2348f4911b21c7da)

**Comment by REAndroid** [comment]
**Fixed on [this commit](https://github.com/REAndroid/ARSCLib/commit/4fe4657f9fd2ec6f3a5fb1ec2348f4911b21c7da)**
