### ISSUE TITLE
Resource path is wrong

### ISSUE THREAD

**Issue by MrIkso** [REAndroid/ARSCLib#10]
Currently your decompiler added "s" for all resource types on when making resource dir 
https://github.com/REAndroid/ARSCLib/blob/bb46abb499a1604c5675aeba3d12b7ca58ab007c/src/main/java/com/reandroid/lib/apk/ResFile.java#L145
It not good. We must a store standard path like menu, drawable, xml, raw etc.

**Comment by REAndroid** [comment]
It was right before some commit, I don't remember why I messed it up. 
Now it is fixed with [this](https://github.com/REAndroid/ARSCLib/commit/b55904f56490d1095fdefd5b963f73fdebcc62cc)
