### ISSUE TITLE
Write bad attr value 

### ISSUE THREAD

**Issue by MrIkso** [REAndroid/ARSCLib#11]
I've used **XML** decompile type. Entry ```@attr/cornerSize``` original  value was **192** but after rebuild from xml
the value is **65472** 

[Files resources_original.arsc and resources_rebuild.arsc](https://drive.google.com/drive/folders/1P6swGassmn4iHVTTFw_EmGyB3C4dm7Nt)

**Comment by MrIkso** [comment]
After rebuilding arsc, your editor writing wrong values in attr

**Comment by REAndroid** [comment]
Method of decompile **XML** or **JSON** ?
What is the type of of attr ? What are the values ?

**Comment by REAndroid** [comment]
Fixed with [this](https://github.com/REAndroid/ARSCLib/commit/1c53bd295c1611498af4a763234987a5e3c68aee)
Thanks , you found serious issue. 
Next time please avoid such large screen shots or crop to min  size possible, or you can say ``` @attr/cornerSize entry value supposed to be 192 but found 65472 ```
