### ISSUE TITLE
Format float

### ISSUE THREAD

**Issue by TimScriptov** [REAndroid/ARSCLib#38]
com.reandroid.arsc.decoder.ComplexUtil$Radix.formatFloat(ComplexUtil.java:156)

`try {
   value = Float.parseFloat(result);
} catch (NumberFormatException ignored) {
 }`

Example log:
`java.lang.NumberFormatException: For input string: "115,199982"`

**Comment by TimScriptov** [comment]
A little later I will throw off the full information, with examples

**Comment by REAndroid** [comment]
The was from string formatter, which depends on default locale. 
Fixed now with latest commit

**Comment by TimScriptov** [comment]
Fixed, thanks

**Comment by TimScriptov** [comment]
![Screenshot_20230504-232543_APK Editor Pro.png](https://user-images.githubusercontent.com/31324315/236295792-f62facb7-ef77-4e77-8ced-273eea560e70.png)

![Screenshot_20230504-232552_APK Editor Pro.png](https://user-images.githubusercontent.com/31324315/236295836-f55fb876-661c-42bd-88a8-6ad03af81c2b.png)

Your library works very well, I replaced ApkTool with your decompiler. I just had to modify your code for a convenient structure 😁

**Comment by REAndroid** [comment]
Good job !
