### ISSUE TITLE
Framework

### ISSUE THREAD

**Issue by TimScriptov** [REAndroid/ARSCLib#39]
Don't use targetSdkVersion for select version framework. Need use compileSdkVersion

**Comment by REAndroid** [comment]
Why?

**Comment by TimScriptov** [comment]
Example:

QQ.apk

AndroidManifest.xml:
targetSdkVersion=26
compileSdkVersion=31

SDK 26 not have `compileSdkVersion` and `compileSdKVersionCodename` and others

Here you need to change the algorithm a little so that it takes the version of the SDK compiler

**Comment by TimScriptov** [comment]
![Screenshot_20230504-234112_APK Editor Pro.png](https://user-images.githubusercontent.com/31324315/236298611-8f18cdba-d0de-49dd-ac2b-e24a2042b1a0.png)

**Comment by TimScriptov** [comment]
Perhaps you should try to combine all the frameworks into one🤷

**Comment by REAndroid** [comment]
Oh you are right, i will fix it soon and maybe I should add option to let user decide which framework version should use.

> Perhaps you should try to combine all the frameworks into one 

It would be better for faster access but we better leave things standard for sake of future changes
