### ISSUE TITLE
Add xml file to apk

### ISSUE THREAD

**Issue by entwildfire** [REAndroid/ARSCLib#44]
Hi, thank you for your great library.
I want to add a new XML file to APK without decompiling the whole APK XML files.
just copy the XML to APK (we have default and v22 version for this resource), index the XML files in resources.arsc, and also modify AndroidManifest and reference this XML in meta-data tag.
I tried doing this as follows:
1. Copy two versions of my XML file (default and v22) to package manually using Winrar to [xml, xml-v22] directories (my APK is not obfuscated). 
2.  index the XML using this code (using some classes from ApkEditor project):
```
ApkModule module=ApkModule.loadApkFile(inputFile);
TableBlock tableBlock = module.getTableBlock();
PackageBlock packageBlock = tableBlock.getPackageBlockById(0x7f);
Entry newEntry = packageBlock.getOrCreate("", "xml", "config");
newEntry.setValueAsString("res/xml/"+ newEntry.getName() +".xml");
Entry newV22Entry = packageBlock.getOrCreate("-v22", "xml", "config");
newV22Entry.setValueAsString("res/xml-v22/"+ newV22Entry.getName() +".xml");
EntryGroup newEntryGroup = new EntryGroup(newEntry.getResourceId());
newEntryGroup.add(newEntry);
newEntryGroup.add(newV22Entry);
packageBlock.getEntriesGroupMap().put(newEntry.getResourceId(), newEntryGroup);
```
3. reference to this XML in the manifest:
```
AndroidManifestBlock manifest = module.getAndroidManifestBlock();
ResXmlElement applicationTag = manifest.getApplicationElement();
List<ResXmlElement> appElements = applicationTag.listElements();
for (ResXmlElement element: appElements) {
    if (element.getAttributeAt(0).getValueString().equals("MyService")) {
        ResXmlElement metaData = element.getElementByTagName("meta-data");
        for (ResXmlAttribute att: metaData.listAttributes()) {
            if (att.getName().equals(AndroidManifestBlock.NAME_resource)) {
                att.setData(newEntry.getResourceId());
            }
        }
    }
}
```
4. package APK:
```
Util.addApkEditorInfo(module, getClass().getSimpleName());
String message = module.refreshTable();
if(message != null){
    log(message);
}
message = module.refreshManifest();
if(message != null){
    log(message);
}

log("Writing apk ...");
module.writeApk(outputFile, this);
log("Saved to: "+outputFile);
log("Done");
```

Because there is no document, I wrote this code by trial and error and I know there are a lot of problems there. and finally, the generated APK looks ok but my config for MyService is not applied. probably there are problems in encoding and obfuscation. also, I don't know what to do if the APK is obfuscated?!

Also, I tried to solve my problem using [this issue](https://github.com/REAndroid/APKEditor/issues/5) and it works. but I want to prevent decoding the whole of APK resources.

**Comment by REAndroid** [comment]
Almost correct:
1. Instead of copying files manually
   - If your xml files are in some directory
   
     ```java
        File fileNewEntry = new File("your_file.xml");
        String pathNewEntry = "res/xml/"+ newEntry.getName() +".xml";
        InputSource inputSource = new FileInputSource(fileNewEntry, pathNewEntry);
        module.add(inputSource);
      ```

   - If your xml files are in another apk, load it in ```ApkModule```
   
     ``` java 
        String pathNewEntry = "res/xml/"+ newEntry.getName() +".xml";
        
        InputSource inputSource = module_2.getInputSource(pathOnModule2);
        // If the path is different
        inputSource.setAlias(pathNewEntry);
        
        module.add(inputSource);
    ``` 
2. You don't need to create ```EntryGroup``` , this class is virtual just for purpose of grouping (summarizing) same resource id with different configs entries and doesn't affect any values.  This class is redundant and affecting performance thus it will be depreciated soon. 

3. Manifest,  Don't use method ```getValueString()``` (Check the comment under source declaration).  

  ```java
        AndroidManifestBlock manifest = module.getAndroidManifestBlock();
        ResXmlElement applicationTag = manifest.getApplicationElement();
        List<ResXmlElement> appElements = applicationTag.listElements();
        for (ResXmlElement element: appElements) {
            ResXmlAttribute nameAttribute = element
                    .searchAttributeByResourceId(AndroidManifestBlock.ID_name);
            if(nameAttribute == null || nameAttribute.getValueType() != ValueType.STRING){
                continue;
            }
            String attributeValue = nameAttribute.getValueAsString();
            if(!"MyService".equals(attributeValue)){
                continue;
            }
            ResXmlElement metaData = element.getElementByTagName("meta-data");
            ResXmlAttribute att = metaData
                    .searchAttributeByResourceId(AndroidManifestBlock.ID_resource);
            att.setTypeAndData(ValueType.REFERENCE, newEntry.getResourceId());
        }
  ```

**Comment by entwildfire** [comment]
Thank you for your answer.
I think there is no problem with adding the XML to resources.arsc, and referencing the XML in the manifest will be fine. The main problem is the XML file, this file is inside an obfuscated APK, and the path dynamically changed after each release and is something like "res/cj.xml" and "res/72.xml" instead of "res/xml/config.xml" and "res/xml-v22/config.xml".
Also, my target APK is not always the same, part of them are not obfuscated and I can use  the real path, but the others are obfuscated, and the XML file paths are like "res/72.xml". I don't know how should i handle all of this dynamicly!

**Comment by entwildfire** [comment]
As I said this process succeed for unobfuscated APKs. but for obfuscated APKs when I create default and v22 resources in the table block, everything looks ok, but the APK created in the result has a problem with the v22 resource. how can I handle this problem? is this library can generate valid resource names for this type of APKs like res/cj.xml?
![Screenshot 2023-06-12 122914](https://github.com/REAndroid/ARSCLib/assets/57716237/2d877f15-13b7-424d-ab02-60e66b3f30e0)

**Comment by entwildfire** [comment]
I think there is a bug in Linux. My code works fine in Windows and everything is ok, but on Ubuntu and Debian the result will be like the above picture. The problem occurs in packing APK. Is there any solution?

**Comment by entwildfire** [comment]
My problem is solved by removing this line:
`Util.addApkEditorInfo(module, getClass().getSimpleName());`
😑
