### ISSUE TITLE
Change package name 

### ISSUE THREAD

**Issue by GiGiDKRS** [REAndroid/ARSCLib#46]
Hello good time

I want to change the package of an application for testing
 
and install the original and edited version side by side

For this, I changed the manifest and a series of elements such as the provider and receiver and meta data
and package element

Using your library, I also changed the resource table (resources.arsc) of the package with this code 

````java
 PackageBlock packageBlock = tableBlock.getPackageArray().get(0);

                packageBlock.setPackageName("com.example.app);
    
````

But again, when installing the edited version next to the original application

The following error is seen
App not installed as package conflicts with an existing package
Thank you for your guidance

**Comment by REAndroid** [comment]
1- Share your used code 
   > For this, I changed the manifest and a series of elements such as the provider and receiver and meta data
and package element

2- Share your exact error message you get from ```adb install file.apk```
