### ISSUE TITLE
Is that possible to decode like this 👇

### ISSUE THREAD

**Issue by developer-krushna** [REAndroid/ARSCLib#7]
<img src="https://user-images.githubusercontent.com/76234660/211707155-0fb3af4e-e1fb-4fe9-9b6d-6ca307c7bf94.jpeg" height="200"/><img src="https://user-images.githubusercontent.com/76234660/211707164-377e4524-b775-4434-a8ef-d2e41964593e.jpeg" height="200"/>
Because I am trying to making something like this..is that possible with this lib sir

**Comment by MrIkso** [comment]
For example im upload [this project ](https://drive.google.com/file/d/1OeS9m_1DEyoTyMLCAMxL3T6Wa1Q9D30Q/view?usp=drivesdk) .

**Comment by developer-krushna** [comment]
> For example im upload [this project ](https://drive.google.com/file/d/1OeS9m_1DEyoTyMLCAMxL3T6Wa1Q9D30Q/view?usp=drivesdk) .



Yes sir you got it right...this is what I need..Thanks for your reply sir ❤️

**Comment by REAndroid** [comment]
**Provide more description for your question**

**Comment by developer-krushna** [comment]
[Arsc Sample.zip](https://github.com/REAndroid/ARSCLib/files/10441529/Arsc.Sample.zip)


Plz sir see the above Decompiled arsc sample...can we do this with the help of this library...☺️..And after edit we can compile the whole folder path to a arsc binary file.. Sir

**Comment by developer-krushna** [comment]
> With ARSCLib you can compile/decompile resources to JSON or XML, if you are java/android developer you can edit resources directly without the need of decompiling

And from your example I experienced that how to patch a arsc file using your library...
**Your example somthing like below**
    public static void exampleResourceTable() throws IOException{
        File inFile=new File("resources.arsc");

        // *** Loading resource table ***
        TableBlock tableBlock=TableBlock.load(inFile);

        Collection<PackageBlock> packageBlockList=tableBlock.listPackages();
        System.out.println("Packages count = "+packageBlockList.size());
        for(PackageBlock packageBlock:packageBlockList){
        System.out.println("Package id = "+packageBlock.getId()
        +", name = "+packageBlock.getName());
        }

        // *** It's a patching method sir ☺️
        // Change package name
        for(PackageBlock packageBlock:packageBlockList){
        String name = packageBlock.getName();
        String newName = name + ".new-name";
        packageBlock.setName(newName);
        }

        // Refresh to re-calculate offsets
        tableBlock.refresh();
        // Save
        File outFile=new File("resources_out.arsc");
        tableBlock.writeBytes(outFile);

**But I want whole arsc resources are Decompiled and saved in a directory..after editing then it should come to normal mode like resources.arsc (binary format)...**

        System.out.println("Saved: "+outFile);
        }

**Comment by REAndroid** [comment]
Did you checked [https://github.com/REAndroid/APKEditor](https://github.com/REAndroid/APKEditor) ?

**Comment by developer-krushna** [comment]
> Did you checked https://github.com/REAndroid/APKEditor ?

Yes sir I checked it ...but I unable to understand the usage.,. If possible please vividly explain me sir ... thank you for giving me your valuable time 🙏

**Comment by developer-krushna** [comment]
> Did you checked https://github.com/REAndroid/APKEditor ?

Sir tell me the usage that how can I convert resources.arsc to XML format and then build back..plz sir tell me the usage of this 🙏

**Comment by MrIkso** [comment]
@developer-krushna see this classes

https://github.com/REAndroid/APKEditor/blob/master/src/main/java/com/reandroid/apkeditor/decompile/Decompiler.java
https://github.com/REAndroid/APKEditor/blob/master/src/main/java/com/reandroid/apkeditor/compile/Builder.java
