### ISSUE TITLE
aapt or aapt2?

### ISSUE THREAD

**Issue by MuntashirAkon** [REAndroid/ARSCLib#8]
Hi,
I've discovered this library while trying to find a solution for this issue: https://github.com/MuntashirAkon/AppManager/issues/951

However, it appears that it is unable to parse the `AndroidManifest.xml` mentioned in the issue just like any other libraries (apksig, jadx, apk-parser, etc.), and throws the following error:

```
java.io.IOException: Not ResXmlBlock: NULL(0x0000){Header=8, Chunk=15756}
	at com.reandroid.lib.arsc.chunk.xml.ResXmlBlock.onReadBytes(ResXmlBlock.java:95)
	at com.reandroid.lib.arsc.base.Block.readBytes(Block.java:38)
```

If it were strictly based on `aapt2` source (which includes the same parser that is included in modern Android OS), it should've been able to parse the file.

Here's the file for reference: [AndroidManifest.xml.pdf](https://github.com/REAndroid/ARSCLib/files/10405352/AndroidManifest.xml.pdf) (remove `.pdf` extension)

Thanks.

PS: This is how it was fixed in LSPatch: https://github.com/LSPosed/LSPatch/commit/c41be02511fd4db6b4d5f47c7f616352bfd128a7

**Comment by REAndroid** [comment]
I don't think this manifest can be parsed by device. On header block chunk type should be 0x3 (XML) but your file is 0x0.

Anyways if you want force load  use class ```UnknownChunk``` 

```java
         BlockReader reader=new BlockReader(new File("AndroidManifest.xml.pdf"));
         UnknownChunk unknownChunk=new UnknownChunk();
         unknownChunk.readBytes(reader);
         unknownChunk.getHeaderBlock().setType(ChunkType.XML);
         BlockReader reader2 = new BlockReader(unknownChunk.getBytes());
         AndroidManifestBlock manifestBlock=new AndroidManifestBlock();
         manifestBlock.readBytes(reader2);
         System.out.println(manifestBlock.getPackageName());
```

**Comment by MuntashirAkon** [comment]
> I don't think this manifest can be parsed by device.

It works in Android and with `aapt2`. So, there must be something missing. I've, of course, attempted to load it as an XML chunk but it didn't work.

> Share one apk to with such manifest.

Here you go: https://upload.disroot.org/r/cGLNRSCB#/ZYIgKSMr4R0KQif91gLCnXF/rNqbIbMwYzny3Z9A3Y=

**Comment by REAndroid** [comment]
- I am surprised aapt2/android allows to parse XML with null chunk type, in the future android might take it as a bug and fix it.
- The resource table of this apk has also weird but valid package header size 340 (normally 284/288). 
- Type names of this apk is also obfuscated, you might get troubles decompiling/compiling to **_XML_** but this is an issue for [APKEditor](https://github.com/REAndroid/APKEditor)

All this issues seems fixed now and thank you for your findings!

**Comment by MuntashirAkon** [comment]
> * I am surprised aapt2/android allows to parse XML with null chunk type, in the future android might take it as a bug and fix it.

This is probably intentional. You can ask in the Google issue tracker, but I don't think they'll answer any technical questions.

> All this issues seems fixed now and thank you for your findings!

Thanks for the quick response. I'll try them out and report back.

**Comment by MuntashirAkon** [comment]
Fixed. Thanks again.
