### ISSUE TITLE
Set indentation for attributes in new lines

### ISSUE THREAD

**Issue by MuntashirAkon** [REAndroid/ARSCLib#9]
There is an option to set indentation for child tags in `XMLDocument` but no option to set indentation for new line attributes and they are at present calculated at `XMLElement#appendAttributesIndentText(Writer)`. It might be better to provide an option to set indentations instead of calculating them. For example, instead of providing an argument `boolean newLineAttributes`, you can provide `int attributeIndentation` whose negative value (e.g. `-1`) would imply no new line and any positive number would imply the amount of indentation.

Thanks.

**Comment by REAndroid** [comment]
I agree , there a lot of other issues to fix on ```com.reandroid.xml.*``` classes.

**Comment by MuntashirAkon** [comment]
Any updates?

**Comment by REAndroid** [comment]
Sorry I don't know how I forgot this issue.
Keeping ```newLineAttributes```, I have added  ```setAttributesIndentScale(float indentScale)``` for elements, you can set negative value to pull back.

**Comment by MuntashirAkon** [comment]
> Keeping `newLineAttributes`, I have added `setAttributesIndentScale(float indentScale)` for elements, you can set negative value to pull back.

It only _scales_ the calculated indentation, it does not _set_ the indentation.

**Comment by REAndroid** [comment]
I feel like i missed your point. As on the last commit you can set indentation to any position you like, I kept  ```newLineAttributes``` param to turn off/on indentation. The indentation for attributes must be calculated bc it is anchored with parent element. 
Can you show me your goal with screenshoot/document ? Or make PR

**Comment by MuntashirAkon** [comment]
I have ended up writing a concrete implementation of XmlPullParser to handle this. As I said in #18, I don't think XML conversion should be part of the library as it can be handled quite easily using XmlSerializer and Transformer functions.
